name: Build on Commit

on:
  push:
    branches: [ '**' ]
    tags: ['**']
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:


  test:
    runs-on: windows-latest


    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: package artifacts for release

        run: |
          cd ${{github.workspace}}\ggml
          7z a ${{github.workspace}}\ggml\turbopilot-${{ runner.os }}-${{ runner.arch }}.zip *.md

      - name: Convert backslashes
        id: convert_backslashes
        run: |
            $path = $env:GITHUB_WORKSPACE -replace '\\', '/'
            echo "Converted path: $path"
            echo "::set-output name=converted_path::$path"
  

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          files: ${{ steps.convert_backslashes.outputs.converted_path }}/ggml/turbopilot-${{ runner.os }}-${{ runner.arch }}.zip